# Generated by Django 4.1 on 2022-11-12 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 17, 59, 14, 64225)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='XpH-nhuQxEUEhsbXKSURr2N9iYhiFdflYitFu-vPEWA', max_length=200),
        ),
    ]
