# Generated by Django 4.1 on 2022-11-17 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 19, 51, 47, 634137)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='cBYqsgHO0J8S9Cfhj64c2PwmcRA3sE2DNPUenGtGlR0', max_length=200),
        ),
    ]
