# Generated by Django 4.1 on 2023-05-04 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 20, 41, 604975)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='Fq1-vl1HM4_RmJgEmS_sPvyxqZj3FZx5V0UIl-ELulA', max_length=200),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='free_time',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
