# Generated by Django 4.1 on 2023-05-04 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_user_profile_phone_user_profile_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 22, 32, 735385)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='0Bk4dXa_Zi69spNNRytjYfFcVjIwWwz90okeF4T3pno', max_length=200),
        ),
    ]
