# Generated by Django 4.1 on 2023-07-25 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_appointment_online_time_slot_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 20, 33, 47, 42934)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='4Lcy0XbIwcAK2VbZ0PPzaOVcyQF6E1RL-HiFGUyxGf0', max_length=200),
        ),
    ]
