# Generated by Django 4.1 on 2022-10-13 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_phone_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='specialist',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 20, 21, 0, 659686)),
        ),
    ]
