# Generated by Django 4.1 on 2023-05-08 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 20, 10, 25, 749383)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='LTBy4m3wFrSfRO4rHX2FF5l1Zro0CVsP2G7uPl3BqWo', max_length=200),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='free_time',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
