# Generated by Django 4.1 on 2023-05-15 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_user_profile_phone_user_profile_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='online',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 20, 29, 17, 735293)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='9TUr1YqttRs2z9z0GfqFB5TNCCbgJ1QkSKrFtl71pbo', max_length=200),
        ),
    ]
