# Generated by Django 4.1 on 2023-05-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='online',
        ),
        migrations.AddField(
            model_name='time_slot',
            name='online',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 20, 40, 53, 159679)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='Zq6HF29K6LoJMlB2Sm3D5GkXDMcAyIp1ZGaLYTuQ6lQ', max_length=200),
        ),
    ]
