# Generated by Django 4.1 on 2022-08-31 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('create_date', models.DateTimeField()),
                ('free_time', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_appointment_create', models.DateTimeField(default=datetime.datetime(2022, 8, 31, 19, 42, 58, 723525))),
                ('time_appointment_delete', models.DateTimeField(blank=True, default=None, null=True)),
                ('description_client', models.TextField(blank=True, default=None, null=True)),
                ('client_phone_number', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=50)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_specialist', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appointment.time_slot')),
            ],
        ),
    ]
