# Generated by Django 4.1 on 2022-10-31 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='sNgxDcfIOkca_HaWzK7g0lBGwrNqNlVXMh13teY7ww4', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 19, 30, 52, 136457)),
        ),
    ]
