# Generated by Django 4.1 on 2022-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modejobspecialist',
            name='future_job_days',
            field=models.IntegerField(default=90),
        ),
    ]
